name: Conditional Workflow

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: silabs-CongD/abc_staging
          ref: master
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install codespell
        run : |
          pip install codespell

          codespell .
