name: CI

on:
  push:

jobs:
  haha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run your steps
        run: exit 0
        
      - name: Run your steps
        run: echo "Must skip hereeeee"
