name: test

on:
  pull_request_target:

jobs:
  readme:
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.check.outputs.repo }}
      # app_token: ${{ steps.
    steps:
    - name: Get repository name
      id: check
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)
        echo "repo=$REPO_NAME" >> $GITHUB_OUTPUT
  
  build:
    runs-on: ubuntu-latest
    outputs:
      build_result: ${{ steps.build_result.outputs.build_result }}
    steps:
    - name: Get repository name
      id: build_result
      run: |
        echo ${{ needs.git_check_change.outputs.repo }}
        echo "build_result=success" >> $GITHUB_OUTPUT
        exit 1
        
        sleep 50
  
  sonar:
    runs-on: ubuntu-latest
    outputs:
      sonar_result: ${{ github.check_sonar.outputs.check_sonar }}
    steps:
    - name: Get repository name
      id: check_sonar
      run: |
        sleep 20
        echo "check_sonar=success" >> $GITHUB_OUTPUT

  approve:
    needs: [readme, build, sonar]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Get repository name
      run: |
        echo ${{ needs.build.outputs.build_result }} 
        echo ${{ needs.sonar.outputs.sonar_result }}
